### ISSUE TITLE
add a version node to each config file

### ISSUE THREAD

**Issue by kinggoesgaming** [hsyyid/EssentialCmds#24]
This helps in keeping track of config updates.

**Comment by dualspiral** [comment]
I have to ask, what is the reason for this? Is it to be able to track when to update the config files? If so, versioning a config file is a bad idea, because a user changing it will have concequences that are difficult to protect against.

Configurate has a really nifty function, `ConfigurationNode::mergeValuesFrom`, that allows you to specify a default set of nodes that won't overwrite the configuration that someone already has. I've used it - my example can be found at https://github.com/dualspiral/Hammer/blob/master/HammerCore/src/main/java/uk/co/drnaylor/minecraft/hammer/core/HammerConfiguration.java#L50. You take the current `ConfigurationNode`, construct a new tree in memory, then on the current node you `mergeValuesFrom`.

I suspect that's what you really want. If so, don't put a version node in each file.

**Comment by kinggoesgaming** [comment]
The method provided by @dualspiral is a much better way of doing stuff so i am closing this issue
